version: '3.8'

services:
  app:
    build: .
    container_name: instagram-bot
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mongo:
        condition: service_started
    environment:
      - TZ=Asia/Tehran 
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/instagram-bot
    networks:
      - app-network
    # افزودن این قسمت
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  mongo:
    image: mongo:latest
    container_name: instagram-bot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local